Ajout des specs fonctionnelles
ansforge/IG-fhir-cahier-de-liaison pull request #9
Opened 2024-07-22 12:23 UTC by nriss

## Description des changements

* [changement 1]
* [changement 2]
* ...

## Preview

https://ansforge.github.io/IG-fhir-cahier-de-liaison/nr-add-sf/ig

2024-08-29 16:17 UTC, sdemeyANS requested changes
qq remarques :)

2024-08-29 16:17 UTC, sdemeyANS commented on input/pagecontent/index.md
> +Les spécifications fonctionnelles s'adresent principalement des chefs de projets ainsi que toute personne concernée par la maîtrise d’ouvrage et qui spécifie des projets avec des interfaces interopér
des fautes d'orthographes :) et phrase pas très claire peut être ?

2024-08-29 16:17 UTC, sdemeyANS commented on input/pagecontent/index.md
> +Il est à noter que les contraintes de sécurité concernant les flux échangés ne sont pas traitées dans ce document. Celles-ci sont du ressort de chaque responsable de l’implémentation du mécanisme qui
peut être ajouter un lien vers la PGSSI-S https://esante.gouv.fr/produits-services/pgssi-s

2024-08-29 16:17 UTC, sdemeyANS commented on input/pagecontent/recherche_note.md
> +| Identifiant de l'auteur de la note   | S’il s’agit d’un professionnel             | author:Prctitioner.identifier | token       |
typo author:Prctitioner

2024-08-29 16:17 UTC, sdemeyANS commented on input/pagecontent/index.md
> +De même, lorsqu’il est fait référence à la ressource Practitioner, PractitionerRole, les profils français « AsProfessionalRoleR », « AsPractitioner » doivent être utilisés.
typo ? AsProfessionalRoleR ?

2024-08-29 16:17 UTC, sdemeyANS commented on input/pagecontent/creation_note.md
> +#### Option transaction
texte un peu compact https://ansforge.github.io/IG-fhir-cahier-de-liaison/nr-add-sf/ig/creation_note.html#option-transaction

2024-08-29 16:17 UTC, sdemeyANS commented on input/pagecontent/recherche_note.md
> +Exemples de requêtes
suggestion : mettre les requêtes dans des balises "code" 
https://ansforge.github.io/IG-fhir-cahier-de-liaison/nr-add-sf/ig/recherche_note.html#flux-4--recherche-de-notes

2024-08-30 08:37 UTC, nriss commented on input/pagecontent/specifications_fonctionnelles.md
> +<div class="figure" style="width:65%;">
J'ai augmenté à 100 mais qualité est nulle, il faudra que je le refasse

2024-08-30 08:38 UTC, nriss commented on input/pagecontent/specifications_fonctionnelles.md
> +<div class="figure" style="width:65%;">
Elle ne sert pas à grand chose en plus

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/874d1c11-5dfc-4fd9-a7ba-483911244775">

2024-08-30 08:38 UTC, nriss commented on input/pagecontent/specifications_fonctionnelles.md
> +<div class="figure" style="width:65%;">
Figure supprimée

2024-09-18 13:45 UTC, sdemeyANS commented on input/pagecontent/specifications_fonctionnelles.md
> +<div class="figure" style="width:65%;">
toujours difficile à lire :(

2024-09-18 14:39 UTC, nriss commented on input/pagecontent/creation_note.md
> +#### Option transaction
C'est corrigé

2024-09-18 14:39 UTC, nriss commented on input/pagecontent/construction_des_flux.md
> +Cette section présente la construction de flux HTTP (de l'API REST FHIR[^18]) pour l'échange des informations identifiées dans les sections précédentes et mises en correspondance avec les éléments de
Fait

2024-09-19 12:57 UTC, sdemeyANS requested changes
un petit problème ici 
<img width="338" alt="image" src="https://github.com/user-attachments/assets/6a5036d9-98e7-425b-a9ed-9224be609e24">

2024-09-19 13:37 UTC, nriss commented
Réglé :)
![image](https://github.com/user-attachments/assets/d7c14dd7-d6de-4484-94ae-4b85c3f1846a)

2024-09-19 14:37 UTC, sdemeyANS approved these changes

2024-09-19 15:11 UTC, merged